# Generated by Django 4.2.26 on 2025-11-17 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='D&H-SHOP', help_text='Nom affiché dans le header et les emails', max_length=100, verbose_name='Nom du site')),
                ('site_tagline', models.CharField(blank=True, default='Votre boutique e-commerce au Gabon', help_text="Phrase d'accroche affichée sous le logo", max_length=200, verbose_name='Slogan/Tagline')),
                ('site_description', models.TextField(blank=True, default='Boutique en ligne proposant des produits de qualité avec livraison rapide.', help_text='Description générale pour le footer et le SEO', verbose_name='Description du site')),
                ('logo', models.ImageField(blank=True, help_text='Logo affiché dans la navbar (recommandé: 200x60px, PNG avec fond transparent)', null=True, upload_to='site_settings/', verbose_name='Logo du site')),
                ('favicon', models.ImageField(blank=True, help_text="Icône affichée dans l'onglet du navigateur (recommandé: 32x32px ou 64x64px, PNG/ICO)", null=True, upload_to='site_settings/', verbose_name='Favicon')),
                ('contact_email', models.EmailField(default='contact@dh-shop.tg', help_text='Email principal pour les demandes clients', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email de contact')),
                ('contact_phone', models.CharField(default='+228 XX XX XX XX', help_text='Numéro principal affiché sur le site', max_length=20, verbose_name='Téléphone de contact')),
                ('contact_whatsapp', models.CharField(blank=True, help_text='Numéro WhatsApp pour le support client (format international)', max_length=20, verbose_name='WhatsApp')),
                ('address_line1', models.CharField(default='123 Rue du Commerce', max_length=255, verbose_name='Adresse ligne 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Adresse ligne 2 (optionnel)')),
                ('city', models.CharField(default='Libreville', max_length=100, verbose_name='Ville')),
                ('country', models.CharField(default='Gabon', max_length=100, verbose_name='Pays')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('business_hours', models.TextField(blank=True, default='Lun - Sam: 8h - 18h\nDimanche: Fermé', help_text='Format libre. Utilisez des retours à la ligne pour séparer les jours', verbose_name="Horaires d'ouverture")),
                ('facebook_url', models.URLField(blank=True, help_text='Lien complet vers votre page Facebook', validators=[django.core.validators.URLValidator()], verbose_name='URL Facebook')),
                ('instagram_url', models.URLField(blank=True, help_text='Lien complet vers votre profil Instagram', validators=[django.core.validators.URLValidator()], verbose_name='URL Instagram')),
                ('twitter_url', models.URLField(blank=True, help_text='Lien complet vers votre profil Twitter/X', validators=[django.core.validators.URLValidator()], verbose_name='URL Twitter/X')),
                ('linkedin_url', models.URLField(blank=True, help_text='Lien complet vers votre page LinkedIn', validators=[django.core.validators.URLValidator()], verbose_name='URL LinkedIn')),
                ('youtube_url', models.URLField(blank=True, help_text='Lien complet vers votre chaîne YouTube', validators=[django.core.validators.URLValidator()], verbose_name='URL YouTube')),
                ('tiktok_url', models.URLField(blank=True, help_text='Lien complet vers votre compte TikTok', validators=[django.core.validators.URLValidator()], verbose_name='URL TikTok')),
                ('meta_title', models.CharField(default='D&H-SHOP - E-Commerce au Gabon', help_text='Titre affiché dans les résultats de recherche (max 70 caractères)', max_length=70, verbose_name='Meta titre (SEO)')),
                ('meta_description', models.CharField(default='Boutique en ligne au Gabon proposant des produits de qualité avec livraison rapide à Libreville.', help_text='Description affichée dans les résultats de recherche (max 160 caractères)', max_length=160, verbose_name='Meta description (SEO)')),
                ('meta_keywords', models.CharField(blank=True, default='ecommerce, gabon, boutique en ligne, livraison, shopping', help_text="Mots-clés séparés par des virgules (optionnel, peu utilisé aujourd'hui)", max_length=255, verbose_name='Meta mots-clés (SEO)')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Format: G-XXXXXXXXXX ou UA-XXXXXXXXX-X', max_length=50, verbose_name='ID Google Analytics')),
                ('facebook_pixel_id', models.CharField(blank=True, help_text='ID du pixel Facebook pour le tracking', max_length=50, verbose_name='ID Facebook Pixel')),
                ('welcome_message', models.TextField(blank=True, default='Bienvenue sur D&H-SHOP ! Profitez de nos offres exceptionnelles.', help_text="Affiché sur la page d'accueil ou en bannière", verbose_name='Message de bienvenue')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Active le mode maintenance (site inaccessible sauf pour les admins)', verbose_name='Mode maintenance')),
                ('maintenance_message', models.TextField(blank=True, default='Site en maintenance. Nous revenons bientôt !', help_text='Message affiché quand le mode maintenance est actif', verbose_name='Message de maintenance')),
                ('newsletter_enabled', models.BooleanField(default=True, help_text="Afficher le formulaire d'inscription à la newsletter", verbose_name='Newsletter active')),
                ('newsletter_description', models.CharField(blank=True, default='Recevez nos offres exclusives', help_text='Texte affiché sous le formulaire newsletter', max_length=200, verbose_name='Description newsletter')),
                ('company_legal_name', models.CharField(blank=True, default='D&H-SHOP SARL', help_text="Nom légal de l'entreprise", max_length=255, verbose_name='Raison sociale')),
                ('company_registration_number', models.CharField(blank=True, help_text='RCCM, SIRET ou équivalent', max_length=100, verbose_name="Numéro d'immatriculation")),
                ('vat_number', models.CharField(blank=True, help_text='Numéro de TVA intracommunautaire si applicable', max_length=100, verbose_name='Numéro TVA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
