# Generated by Django 4.2.26 on 2025-11-14 11:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        ('shop', '0002_alter_product_name_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code promo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe')], default='percentage', max_length=20, verbose_name='Type de réduction')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valeur de la réduction')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Montant maximum de réduction (pour les pourcentages)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Réduction maximum')),
                ('minimum_purchase', models.DecimalField(decimal_places=2, default=0, help_text="Montant minimum d'achat requis", max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Achat minimum')),
                ('usage_limit', models.IntegerField(blank=True, help_text="Nombre maximum d'utilisations (vide = illimité)", null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Limite d'utilisation totale")),
                ('usage_limit_per_customer', models.IntegerField(default=1, help_text="Nombre d'utilisations par client", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Limite par client')),
                ('times_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre d'utilisations")),
                ('valid_from', models.DateTimeField(verbose_name='Valide à partir de')),
                ('valid_until', models.DateTimeField(verbose_name="Valide jusqu'à")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la promotion')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('promotion_type', models.CharField(choices=[('product', 'Produit spécifique'), ('category', 'Catégorie'), ('global', 'Globale (tout le site)')], default='product', max_length=20, verbose_name='Type de promotion')),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe')], default='percentage', max_length=20, verbose_name='Type de réduction')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valeur de la réduction')),
                ('valid_from', models.DateTimeField(verbose_name='Valide à partir de')),
                ('valid_until', models.DateTimeField(verbose_name="Valide jusqu'à")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_stackable', models.BooleanField(default=False, help_text="Peut être combinée avec d'autres promotions", verbose_name='Empilable')),
                ('priority', models.IntegerField(default=0, help_text='Priorité (plus élevé = appliqué en premier)', verbose_name='Priorité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='shop.category', verbose_name='Catégories')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='shop.product', verbose_name='Produits')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant de la réduction')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Utilisé le')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='marketing.coupon', verbose_name='Coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='accounts.customer', verbose_name='Client')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='orders.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Utilisation de coupon',
                'verbose_name_plural': 'Utilisations de coupons',
                'ordering': ['-used_at'],
            },
        ),
    ]
