# Generated by Django 4.2.26 on 2025-11-16 00:36

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('stock_low', 'Stock faible'), ('stock_out', 'Rupture de stock'), ('orders_pending', 'Commandes en attente'), ('revenue_drop', 'Baisse du CA'), ('customer_inactive', 'Clients inactifs'), ('payment_failed', 'Paiements échoués'), ('custom', 'Alerte personnalisée')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('danger', 'Critique')], default='info', max_length=20)),
                ('threshold_value', models.IntegerField(blank=True, help_text="Valeur seuil qui déclenche l'alerte", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('notify_by_email', models.BooleanField(default=False, help_text='Envoyer une notification par email')),
                ('email_recipients', models.TextField(blank=True, help_text='Emails des destinataires (un par ligne)')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Alerte Dashboard',
                'verbose_name_plural': 'Alertes Dashboard',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['is_active', 'is_resolved', '-triggered_at'], name='dashboard_d_is_acti_938e4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_orders', models.IntegerField(default=0)),
                ('orders_today', models.IntegerField(default=0)),
                ('orders_month', models.IntegerField(default=0)),
                ('pending_orders', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('revenue_today', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('revenue_month', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_products', models.IntegerField(default=0)),
                ('out_of_stock', models.IntegerField(default=0)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('total_customers', models.IntegerField(default=0)),
                ('new_customers_month', models.IntegerField(default=0)),
                ('active_customers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes optionnelles sur ce snapshot')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot Dashboard',
                'verbose_name_plural': 'Snapshots Dashboard',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['-snapshot_date'], name='dashboard_d_snapsho_afcb4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action_type', models.CharField(choices=[('order_edit', 'Modification de commande'), ('order_cancel', 'Annulation de commande'), ('order_refund', 'Remboursement'), ('stock_update', 'Mise à jour stock'), ('product_edit', 'Modification produit'), ('customer_edit', 'Modification client'), ('settings_change', 'Changement configuration'), ('export_data', 'Export de données'), ('other', 'Autre')], db_index=True, max_length=50)),
                ('action_description', models.TextField(help_text="Description détaillée de l'action effectuée")),
                ('object_type', models.CharField(blank=True, help_text="Type d'objet concerné (Order, Product, etc.)", max_length=50)),
                ('object_id', models.IntegerField(blank=True, help_text="ID de l'objet concerné", null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('data_before', models.JSONField(blank=True, help_text="État de l'objet avant modification (JSON)", null=True)),
                ('data_after', models.JSONField(blank=True, help_text="État de l'objet après modification (JSON)", null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'activité admin",
                'verbose_name_plural': "Logs d'activité admin",
                'ordering': ['-action_date'],
                'indexes': [models.Index(fields=['-action_date'], name='dashboard_a_action__745ae3_idx'), models.Index(fields=['user', '-action_date'], name='dashboard_a_user_id_98a7ba_idx'), models.Index(fields=['action_type', '-action_date'], name='dashboard_a_action__077019_idx')],
            },
        ),
    ]
