# Generated by Django 4.2.26 on 2025-11-14 11:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format : '+999999999'. 9 à 15 chiffres.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='customers/profiles/', verbose_name='Photo de profil')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='Notifications par SMS')),
                ('whatsapp_notifications', models.BooleanField(default=False, verbose_name='Notifications par WhatsApp')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Nombre total de commandes')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total dépensé')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Compte bloqué')),
                ('block_reason', models.TextField(blank=True, verbose_name='Raison du blocage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrit le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format : '+999999999'. 9 à 15 chiffres.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Adresse ligne 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Adresse ligne 2 (optionnel)')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Région/État')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(default='Togo', max_length=100, verbose_name='Pays')),
                ('address_type', models.CharField(choices=[('shipping', 'Livraison'), ('billing', 'Facturation')], default='shipping', max_length=10, verbose_name="Type d'adresse")),
                ('is_default', models.BooleanField(default=False, verbose_name='Adresse par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.customer', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
