"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, UndefinedValueError
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# ========================================
# SÉCURITÉ : SECRET_KEY
# ========================================
try:
    SECRET_KEY = config('SECRET_KEY')
except UndefinedValueError:
    raise ValueError("❌ ERREUR CRITIQUE : La variable SECRET_KEY n'est pas définie dans le fichier .env")

DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'dashboard.apps.DashboardConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    'crispy_forms',
    'crispy_bootstrap5',
    
    'core.apps.CoreConfig',
    'shop',
    'orders',
    'accounts',
    'payments',
    'adminpanel',
    'marketing',
]

# ========================================
# MIDDLEWARE - WHITENOISE OBLIGATOIRE
# ========================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ✅ TOUJOURS ACTIVÉ
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# SUPPRIMER le bloc try/except WhiteNoise (lignes 73-81)

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'core.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ========================================
# BASE DE DONNÉES - SUPPORT DÉVELOPPEMENT & PRODUCTION
# ========================================

# Production Render : Utiliser DATABASE_URL (PostgreSQL)
if config('DATABASE_URL', default=None):
    DATABASES = {
        'default': dj_database_url.config(
            default=config('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Développement local : MySQL
    try:
        DB_PASSWORD = config('DB_PASSWORD')
    except UndefinedValueError:
        raise ValueError("❌ ERREUR CRITIQUE : DB_PASSWORD non définie dans .env")
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('DB_NAME', default='ecommerce_db'),
            'USER': config('DB_USER', default='root'),
            'PASSWORD': DB_PASSWORD,
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='3306'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
            },
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Libreville'
USE_I18N = True
USE_TZ = True


# ========================================
# FICHIERS STATIQUES - CORRECTION PRODUCTION
# ========================================
STATIC_URL = '/static/'

# ✅ CORRECTION : STATICFILES_DIRS seulement en développement
if DEBUG:
    STATICFILES_DIRS = [
        BASE_DIR / 'static',
    ]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# ✅ CORRECTION : Configuration moderne STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ========================================
# STOCKAGE CLOUDINARY (Production)
# ========================================
if not DEBUG:
    # Ajouter Cloudinary aux applications
    INSTALLED_APPS = [
        'cloudinary_storage',
        'cloudinary',
    ] + INSTALLED_APPS
    
    # Configuration Cloudinary
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME', default=''),
        'API_KEY': config('CLOUDINARY_API_KEY', default=''),
        'API_SECRET': config('CLOUDINARY_API_SECRET', default=''),
    }
    
    # Remplacer le stockage par défaut par Cloudinary
    STORAGES['default'] = {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    }


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Crispy Forms Configuration
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# Authentication
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'accounts:dashboard'
LOGOUT_REDIRECT_URL = 'core:home'


# ========================================
# CONFIGURATION CACHE (CORRIGÉE DÉFINITIVEMENT)
# ========================================
# FORCER le cache en mémoire - NE JAMAIS utiliser Redis sauf configuration explicite
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}


# ========================================
# CONFIGURATION EMAIL
# ========================================
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

if EMAIL_BACKEND == 'django.core.mail.backends.smtp.EmailBackend':
    if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
        raise ValueError("❌ ERREUR : Identifiants SMTP manquants")

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@votreboutique.com')
DEFAULT_FROM_NAME = config('DEFAULT_FROM_NAME', default='E-Commerce Gabon')
ADMINS = [('Admin', config('ADMIN_EMAIL', default='admin@votreboutique.com'))]
SERVER_EMAIL = DEFAULT_FROM_EMAIL


# ========================================
# INFORMATIONS DE LA BOUTIQUE
# ========================================
SITE_NAME = config('SITE_NAME', default='Ma Boutique E-Commerce')
SHOP_NAME = config('SHOP_NAME', default='E-Commerce Gabon')
SHOP_EMAIL = config('SHOP_EMAIL', default='contact@ecommerce-gabon.com')
SHOP_PHONE = config('SHOP_PHONE', default='+241 XX XX XX XX')
SHOP_ADDRESS = config('SHOP_ADDRESS', default='Libreville, Gabon')
SHOP_WEBSITE = config('SHOP_WEBSITE', default='http://localhost:8000')
SHOP_LOGO_URL = config('SHOP_LOGO_URL', default='')

COMPANY_ADDRESS = SHOP_ADDRESS
COMPANY_PHONE = SHOP_PHONE
COMPANY_EMAIL = SHOP_EMAIL

SOCIAL_FACEBOOK = config('SOCIAL_FACEBOOK', default='')
SOCIAL_INSTAGRAM = config('SOCIAL_INSTAGRAM', default='')
SOCIAL_TWITTER = config('SOCIAL_TWITTER', default='')


# ========================================
# CONFIGURATION PAIEMENT MOBILE
# ========================================
MOOV_API_KEY = config('MOOV_API_KEY', default='')
MOOV_API_SECRET = config('MOOV_API_SECRET', default='')
AIRTEL_API_KEY = config('AIRTEL_API_KEY', default='')
AIRTEL_API_SECRET = config('AIRTEL_API_SECRET', default='')


# ========================================
# LOGGING
# ========================================
LOGS_DIR = BASE_DIR / 'logs'
if not LOGS_DIR.exists():
    LOGS_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'app.log',
            'formatter': 'verbose',
        },
        'email_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'email.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'core.email_service': { 'handlers': ['console', 'email_file'], 'level': 'INFO', 'propagate': False },
        'core.pdf_service': { 'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False },
        'accounts': { 'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False },
        'orders': { 'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False },
        'payments': { 'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False },
        'dashboard': { 'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False },
    },
}


# ========================================
# SÉCURITÉ (Activé seulement en production)
# ========================================
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False