# Generated by Django 4.2.26 on 2025-11-15 13:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la zone')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('covered_cities', models.TextField(help_text='Liste des villes/quartiers couverts (séparés par des virgules). Ex: Libreville, Owendo, Akanda', verbose_name='Villes couvertes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Zone active')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('standard_delivery_days_min', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Délai standard minimum (jours)')),
                ('standard_delivery_days_max', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Délai standard maximum (jours)')),
                ('express_delivery_days_min', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Délai express minimum (jours)')),
                ('express_delivery_days_max', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Délai express maximum (jours)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
            ],
            options={
                'verbose_name': 'Zone de livraison',
                'verbose_name_plural': 'Zones de livraison',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express')], default='standard', max_length=20, verbose_name='Type de livraison'),
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('standard', 'Livraison Standard'), ('express', 'Livraison Express')], max_length=20, verbose_name='Type de livraison')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix (FCFA)')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant minimum de commande pour bénéficier de ce tarif. 0 = aucune limite', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant minimum de commande')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Montant à partir duquel la livraison devient gratuite. Laisser vide = jamais gratuit', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seuil livraison gratuite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Tarif actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='orders.shippingzone', verbose_name='Zone de livraison')),
            ],
            options={
                'verbose_name': 'Tarif de livraison',
                'verbose_name_plural': 'Tarifs de livraison',
                'ordering': ['zone__display_order', 'delivery_type'],
                'unique_together': {('zone', 'delivery_type')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.shippingrate', verbose_name='Tarif de livraison'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.shippingzone', verbose_name='Zone de livraison'),
        ),
    ]
