# Generated by Django 4.2.26 on 2025-11-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_shippingzone_order_delivery_type_shippingrate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_index=True, help_text='Préfixe basé sur la date (ex: 20250119)', max_length=20, unique=True, verbose_name='Préfixe')),
                ('last_number', models.IntegerField(default=0, help_text='Dernier numéro séquentiel utilisé pour ce préfixe', verbose_name='Dernier numéro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Séquence de numéro de commande',
                'verbose_name_plural': 'Séquences de numéros de commande',
                'ordering': ['-prefix'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, help_text='Généré automatiquement par le service', max_length=50, unique=True, verbose_name='Numéro de commande'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='idx_order_number'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='idx_customer_date'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='idx_status'),
        ),
        migrations.AddIndex(
            model_name='ordernumbersequence',
            index=models.Index(fields=['prefix'], name='idx_prefix'),
        ),
    ]
